config/routes.rb
Rails.application.routes.draw do
  resources :items do
    collection do
      post :random_create
      get :create_random
      post :create_random
      post :get_item_name
      post :create_item
    end
    member do
      post :destroy
      post :get_item_name
      post :create_item
    end
    resources :effects, only: [:new, :create, :edit, :update]
  end
  resources :categories

  resources :effects do
    collection do
      post :get_effects_by_category
    end
    member do
      post :get_effects_by_category
    end
  end

  resources :rarities do
    collection do
      post :get_rarities
    end
  end
  resources :weapons

  root 'main#index'
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/create.html.erb
<h1>Main#create</h1>
<p>Find me in app/views/main/create.html.erb</p>

app/views/main/destroy.html.erb
<h1>Main#destroy</h1>
<p>Find me in app/views/main/destroy.html.erb</p>

app/views/main/edit.html.erb
<h1>Main#edit</h1>
<p>Find me in app/views/main/edit.html.erb</p>

app/views/main/index.html.erb
<%= render "layouts/subheader", :locals => {:count => 0, :name => "Home"} %>

<div class="container text-center mt-3">
	<div class="row card-group">
		<div class="card" style="max-width: 800px; margin: 25px; border: 1px solid gray; border-radius: 0 0 15px 15px; padding: 0">
			<%= image_tag "hero.png", alt: "Hero Image", class: "img-fluid" %>
		  <div class="card-body">
		    <h5 class="card-title">Create Random Object</h5>
		    <p class="card-text">We can create a new object.</p>
		    <%= link_to 'Create Random Item', create_random_items_path, class: 'btn btn-outline-success' %>	    
		  </div>
		</div>

		<div class="card" style="margin: 25px; border: 1px solid gray; border-radius: 5px; padding: 0">
			<%= image_tag "hero3.png", alt: "Hero Image", class: "img-fluid" %>
			<hr class="cool-hr">
		  <div class="card-body">
		    <h5 class="card-title">Handle Effects</h5>
		    <p class="card-text">We can handle effects</p>
		    <%= link_to 'Effects', effects_path, class: 'btn btn-outline-primary' %>
		  </div>
		</div>

	</div>

	<hr class="cool-hr">

	<div class="row card-group">
		<div class="card" style="margin: 25px; border: 1px solid gray; border-radius: 5px; padding: 0">
			<%= image_tag "hero6.png", alt: "Hero Image", class: "img-fluid" %>
		  <div class="card-body">
		    <h5 class="card-title">Rarities</h5>
		    <p class="card-text">We can edit rarities for objects</p>
		    <%= link_to 'Items', rarities_path, class: 'btn btn-outline-primary' %>
		  </div>
		</div>

		<div class="card" style="max-width: 320px;margin: 25px; border: 1px solid gray; border-radius: 5px; padding: 0">
			<%= image_tag "hero2.png", alt: "Hero Image", class: "img-fluid" %>
		  <div class="card-body">
		    <h5 class="card-title">Items</h5>
		    <p class="card-text">We can handle items</p>
		    <%= link_to 'Effects', items_path, class: 'btn btn-outline-secondary' %>
		  </div>
		</div>

		<div class="card" style="max-width: 320px;margin: 25px; border: 1px solid gray; border-radius: 5px; padding: 0">
			<%= image_tag "hero4.png", alt: "Hero Image", class: "img-fluid" %>
		  <div class="card-body">
		    <h5 class="card-title">Categories</h5>
		    <p class="card-text">We can handle categories</p>
		    <%= link_to 'Categories', categories_path, class: 'btn btn-outline-info' %>
		  </div>
		</div>

		<div class="card" style="max-width: 320px;margin: 25px; border: 1px solid gray; border-radius: 5px; padding: 0">
			<%= image_tag "hero5.png", alt: "Hero Image", class: "img-fluid" %>
		  <div class="card-body">
		    <h5 class="card-title">Weapons</h5>
		    <p class="card-text">We can handle weapons</p>
		    <%= link_to 'Weapons', weapons_path, class: 'btn btn-outline-danger' %>
		  </div>
		</div>
	</div>
</div>

app/views/main/new.html.erb
<h1>Main#new</h1>
<p>Find me in app/views/main/new.html.erb</p>

app/views/main/show.html.erb
<h1>Main#show</h1>
<p>Find me in app/views/main/show.html.erb</p>

app/views/main/update.html.erb
<h1>Main#update</h1>
<p>Find me in app/views/main/update.html.erb</p>