config/routes.rb
Rails.application.routes.draw do
  resources :items do
    collection do
      post :random_create
      get :create_random
      post :create_random
      post :get_item_name
      post :create_item
    end
    member do
      post :destroy
      post :get_item_name
      post :create_item
    end
    resources :effects, only: [:new, :create, :edit, :update]
  end
  resources :categories

  resources :effects do
    collection do
      post :get_effects_by_category
    end
    member do
      post :get_effects_by_category
    end
  end

  resources :rarities do
    collection do
      post :get_rarities
    end
  end
  resources :weapons

  root 'main#index'
end

app/models/rarity.rb
class Rarity < ApplicationRecord
  has_many :items

  validates :name, presence: true, uniqueness: true
  validates :min_price, :max_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validate :min_price_less_than_max_price

  private

  def min_price_less_than_max_price
    if min_price.present? && max_price.present? && min_price > max_price
      errors.add(:min_price, "must be less than or equal to max price")
    end
  end
end
	

app/controllers/rarities_controller.rb
class RaritiesController < ApplicationController
  before_action :set_rarity, only: [:show, :edit, :update, :destroy]

  def index
    @rarities = Rarity.all
  end

  def new
    @rarity = Rarity.new
  end

  def create
    @rarity = Rarity.new(rarity_params)
    if @rarity.save
      redirect_to rarities_path, notice: "Rarity created successfully."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @rarity.update(rarity_params)
      redirect_to rarities_path, notice: "Rarity updated successfully."
    else
      render :edit
    end
  end

  def destroy
    @rarity.destroy
    redirect_to rarities_path, notice: "Rarity deleted successfully."
  end

  def get_rarities
    rarities = Rarity.all

    respond_to do |format|
      format.json { render json: { status: 'success', data: rarities }}
    end
  end

  private

  def set_rarity
    @rarity = Rarity.find(params[:id])
  end

  def rarity_params
    params.require(:rarity).permit(:name, :min_price, :max_price)
  end
end

app/helpers/rarities_helper.rb
module RaritiesHelper
end

app/views/rarities/create.html.erb
<h1>Rarities#create</h1>
<p>Find me in app/views/rarities/create.html.erb</p>

app/views/rarities/destroy.html.erb
<h1>Rarities#destroy</h1>
<p>Find me in app/views/rarities/destroy.html.erb</p>

app/views/rarities/edit.html.erb
<h1>Rarities#edit</h1>
<p>Find me in app/views/rarities/edit.html.erb</p>

app/views/rarities/index.html.erb
<%= render "layouts/subheader", :locals => {:count => @rarities.count, :name => "Rarities"} %>

<div class="container mt-3">  
	<table class="table table-bordered table-hover table-striped">
	  <thead class="table-primary">
	    <tr>
	      <th>Name</th>
	      <th>Price Range (GC)</th>
	      <th>Power Range</th>
	      <th>Actions</th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @rarities.each do |rarity| %>
	      <tr>
	        <td><%= rarity.name %></td>
	        <td><%= "#{rarity.min_price} - #{rarity.max_price}" %></td>
	        <td><%= "#{rarity.min_power} - #{rarity.max_power}" %></td>
	        <td style="min-width: 185px;">
            <%= link_to 'Show', rarity_path(rarity), class: "btn btn-outline-primary btn-sm" %>
            <%= link_to 'Edit', edit_rarity_path(rarity), class: "btn btn-outline-success btn-sm" %>
            <%= link_to 'Delete', rarity_path(rarity), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
          </td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>

app/views/rarities/new.html.erb
<h1>Rarities#new</h1>
<p>Find me in app/views/rarities/new.html.erb</p>

app/views/rarities/show.html.erb
<h1>Rarities#show</h1>
<p>Find me in app/views/rarities/show.html.erb</p>

app/views/rarities/update.html.erb
<h1>Rarities#update</h1>
<p>Find me in app/views/rarities/update.html.erb</p>