config/routes.rb
Rails.application.routes.draw do
  resources :items do
    collection do
      post :random_create
      get :create_random
      post :create_random
      post :get_item_name
      post :create_item
    end
    member do
      post :destroy
      post :get_item_name
      post :create_item
    end
    resources :effects, only: [:new, :create, :edit, :update]
  end
  resources :categories

  resources :effects do
    collection do
      post :get_effects_by_category
    end
    member do
      post :get_effects_by_category
    end
  end

  resources :rarities do
    collection do
      post :get_rarities
    end
  end
  resources :weapons

  root 'main#index'
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  validates :name, presence: true
  validates :cost, :weight, numericality: { greater_than_or_equal_to: 0 }
  validates :damage, presence: true
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  def index
    @weapons = Weapon.all
  end

  def show
    @weapon = Weapon.find(params[:id])
  end

  def new
    @weapon = Weapon.new
  end

  def create
    @weapon = Weapon.new(weapon_params)
    if @weapon.save
      redirect_to @weapon, notice: "Weapon successfully created."
    else
      render :new
    end
  end

  def edit
    @weapon = Weapon.find(params[:id])
  end

  def update
    @weapon = Weapon.find(params[:id])
    if @weapon.update(weapon_params)
      redirect_to @weapon, notice: "Weapon successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @weapon = Weapon.find(params[:id])
    @weapon.destroy
    redirect_to weapons_path, notice: "Weapon successfully deleted."
  end

  private

  def weapon_params
    params.require(:weapon).permit(:name, :cost, :damage, :weight, :properties)
  end
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/weapons/_form.html.erb
<%= form_with(model: weapon, local: true) do |form| %>
  <% if weapon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>
      <ul>
        <% weapon.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>
  <div>
    <%= form.label :damage %>
    <%= form.text_field :damage %>
  </div>
  <div>
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>
  <div>
    <%= form.label :properties %>
    <%= form.text_area :properties %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/weapons/edit.html.erb
<%= render 'form', weapon: @weapon %>
<%= link_to 'Back', weapons_path %>

app/views/weapons/index.html.erb
<%= render "layouts/subheader", :locals => {:count => @weapons.count, :name => "Weapons"} %>

<div class="container mt-3">
  <table class="table table-hover table-bordered table-striped">
    <thead class="table-primary">
      <tr>
      <th>Name</th>
      <th>Cost</th>
      <th>Damage</th>
      <th>Weight</th>
      <th>Properties</th>
      <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @weapons.each do |weapon| %>
        <tr>
          <td><%= weapon.name %></td>
          <td><%= weapon.cost %></td>
          <td><%= weapon.damage %></td>
          <td><%= weapon.weight %></td>
          <td><%= weapon.properties %></td>
          </td>
          <td style="min-width: 185px;">
            <%= link_to 'Show', weapon_path(weapon), class: "btn btn-outline-primary btn-sm" %>
            <%= link_to 'Edit', edit_weapon_path(weapon), class: "btn btn-outline-success btn-sm" %>
            <%= link_to 'Delete', weapon_path(weapon), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/weapons/new.html.erb
<%= render 'form', weapon: @weapon %>
<%= link_to 'Back', weapons_path %>

app/views/weapons/show.html.erb
<h1><%= @weapon.name %></h1>
<p><strong>Cost:</strong> <%= @weapon.cost %></p>
<p><strong>Damage:</strong> <%= @weapon.damage %></p>
<p><strong>Weight:</strong> <%= @weapon.weight %> lbs</p>
<p><strong>Properties:</strong> <%= @weapon.properties %></p>
<%= link_to 'Edit', edit_weapon_path(@weapon) %> |
<%= link_to 'Back', weapons_path %>