config/routes.rb
Rails.application.routes.draw do
  resources :items do
    collection do
      post :random_create
      get :create_random
      post :create_random
      post :get_item_name
      post :create_item
    end
    member do
      post :destroy
      post :get_item_name
      post :create_item
    end
    resources :effects, only: [:new, :create, :edit, :update]
  end
  resources :categories

  resources :effects do
    collection do
      post :get_effects_by_category
    end
    member do
      post :get_effects_by_category
    end
  end

  resources :rarities do
    collection do
      post :get_rarities
    end
  end
  resources :weapons

  root 'main#index'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :rarity
  has_many :item_effects
  has_many :effects, through: :item_effects

  validates :name, presence: true
  validates :item_type, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
    @weapons = Weapon.all
    @categories = Category.all
    @rarities = Rarity.all
    @effects = Effect.all
  end

  def create_item
    item_name = params[:name]
    rarity_name = params[:rarity]
    rarity = Rarity.find_by(name: rarity_name)
    category_id = params[:category] || ""
    weapon = params[:weapon] || ""
    power = params[:power].to_i || 0
    effect_ids = params[:effects] || []

    category = Category.find(category_id)
    effects = Effect.find(effect_ids)

    item = Item.create!(
      name:               item_name,
      category:           category,
      rarity:             rarity,
      description:        "A very interesting item with mysterious properties.",
      item_type:          "item type",
      power:              power,
      weight:             rand(category.min_weight..category.max_weight),
      price:              getPrice(rarity),
      requires_attunement: power > 2,
    )

    item.effects = effects
    item.save!
    
    respond_to do |format|
      format.json {
        render json: { 
          status: 'success',
          data: "Item created! #{item_name} | Power: #{power}"
        }
      }
    end
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def edit

    @item = Item.find(params[:id])

    @weapons = Weapon.all
    @categories = Category.all
    @rarities = Rarity.all
    @effects = Effect.all

    # @selectedCategory = 
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.item_effects.destroy_all    
    @item.destroy
    redirect_to items_path, notice: 'Item was successfully removed.'
  end

  def getPrice(rarity)
    price = rand(rarity.min_price..rarity.max_price).round(-1)
    price_length = price.to_s.length
    rounded_price = price.round(-(price_length - 2))
  end

  # Create Random Items
  def create_random
    @categories = Category.all
    @power_levels = (1..10).to_a
    @rarities = Rarity.all

    power = params[:power_level]
    category_id = params[:category_id]
    commit = params[:commit]

    if commit == "Generate Fully Random Item"
      random_create(rand(1..10), Category.all.sample.id)
    end
    return unless power.present? && category_id.present? && commit.present?

    if commit == "Generate Item"
      random_create(power.to_i, category_id)
    end
  end

  def random_create(power, category_id)
    category = Category.find(category_id.to_i)
    rarity_name = getRarity(power)
    rarity = Rarity.find_by(name: rarity_name)
    
    item = Item.create!(
      name:                "temp name",
      category:            category,
      rarity:              rarity,
      description:         "A very interesting item with mysterious properties.",
      item_type:           "item type",
      power:               power,
      weight:              rand(category.min_weight..category.max_weight),
      price:               rand(rarity.min_price..rarity.max_price),
      requires_attunement: power > 2,
    )

    available_power = item.power

    if category.name == "Weapons"
      effect = addAttackEffect(available_power, category, "Attack Bonus")
      item.effects << effect
      available_power -= effect.power_level

      if available_power > 0
        effect = addAttackEffect(available_power, category, "Attack Damage")
        item.effects << effect
        available_power -= effect.power_level
      end
    end

    while available_power > 0 do
      effect_types = []
      item.effects.each do |effect|
        effect_types << effect.effect_type
      end
   
      effect = getEffect(available_power, category, effect_types)
      break if effect.nil?

      item.effects << effect if effect.present?
      available_power -= effect.power_level
    end

    item.name = item_name = getItemName(rarity_name, item.effects, category, nil)

    item.save!
  end

  def get_item_name
    category_id = params[:category] || ""
    weapon = params[:weapon] || ""
    power = params[:power] || 0
    effect_ids = params[:effects] || []

    rarity_name = getRarity(power.to_i)
    category = Category.find(category_id)
    effects = Effect.find(effect_ids)
    
    name = getItemName(rarity_name, effects, category, weapon)

    respond_to do |format|
      format.json { render json: { status: 'success', data: name }}
    end

  end

  private
    def addAttackEffect(power, category, effect_type)
      min_power, max_power =  case power
                                when 5..10 then [2, 5]
                                when 4 then [1, 4]
                                when 3 then [0, 3]
                                when 2 then [0, 2]
                                else [0, 1]
                              end

      Effect.joins(:categories)
            .where(categories: { id: category.id })
            .where(effect_type: effect_type)
            .where(power_level: min_power..max_power)
            .sample
    end

    def getRarity(power)
      rarity = case power
                when 0..1 then "Common"
                when 2..3 then "Uncommon"
                when 4..5 then "Rare"
                when 6..7 then "Very Rare"
                when 8..9 then "Legendary"
                when 10 then "Ancestral"
               end
      rarity
    end

    def getCategory
    end

    def getEffect(power, category, effect_types)
      Effect.joins(:categories)
            .where(categories: { id: category.id })
            .where.not(effect_type: effect_types)
            .where("power_level <= ?", power)
            .sample
    end

    def getWeaponType
      Weapon.all.sample.name
    end

    def getRarityName(rarity_name)
      rarity_options = {
          "Common"    => ["Simple", "Regular", "Mundane", "Acceptable", "Mediocre", "Consistent", "Ordinary", "Usual", "Normal", "Plain", "Routine", "Standard", "Typical", "Familiar", "Generic"],
          "Uncommon"  => ["Good", "Improved", "Promising", "Advantageous", "Competent", "Helpful", "Respected", "Remarkable", "Noble", "Uncommon", "Distinct", "Noteworthy", "Notable", "Beneficial", "Unique"],
          "Rare"      => ["Powerful", "Great", "Prestigious", "Outstanding", "Exceptional", "Admirable", "Premium", "Notable", "Superior", "Renowned", "Exclusive", "Valuable", "Esteemed", "Rare", "Select"],
          "Very Rare" => ["Amazing", "Spectacular", "Omniscient", "Chivalrous", "Marvelous", "Iconic", "Celestial", "Exquisite", "Eminent", "Admirable", "Astonishing", "Incredible", "Phenomenal", "Mystical", "Unrivaled"],
          "Legendary" => ["Legendary", "Overpowered", "Magnificent", "Heroic", "Immortalized", "Fabled", "Exalted", "Arcane", "Timeless", "Supreme", "Unmatched", "Divine", "Unparalleled", "Sovereign", "Glorious", "Imperial"],
          "Ancestral" => ["Ancestral", "Mythic", "Epic", "Primordial", "Primal", "Transcendent", "Divine", "Eternal", "Celestial", "Infinite", "Ancient", "Cosmic", "Primeval", "Originating", "Boundless"]
        }

      rarity_options[rarity_name]&.sample
    end

    def getCategoryName(category)
      category.name == "Weapons" ? getWeaponType : category.name
    end

    def getItemName(rarity, effects, category, weapon)
      rarity_name = getRarityName(rarity)
      
      category_name = (category.name == "Weapons" && weapon.present?) ? weapon : getCategoryName(category)

      effect_types = effects.pluck(:effect_type).sample
      # effect_categories_names = effects.pluck(:name).sample # join(", ")

      name_parts = []
      name_parts << "#{rarity_name}"
      name_parts << "#{category_name}"
      name_parts << "#{effect_types.present? ? "of #{effect_types}" : ''}" 
      # name_parts << "with #{effect_categories_names}" if effect_categories_names.present?

      name_parts.join(" ")
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :description, :item_type, :rarity, :category_id, :price, :weight, :category, :power, effects: [])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="container mt-5">
  <h2>Create a New Item</h2>

  <%= form_with(model: @item, local: true) do |form| %>
    <!-- Select Name -->
    <div class="form-group mb-3">
      <%= form.label :name, 'Item Name', class: "form-label" %>
      <div class="input-group">
        <%= form.text_field :name, class: 'form-control', placeholder: 'Enter item name' %>
        <button id="generateNameBtn" class="btn btn-outline-primary">Generate</button>
      </div>
    </div>

    <!-- Select Category -->
    <div class="form-group mb-3">
      <%= form.label :category_id, 'Select Category', class: "form-label" %>
      <br>

      <select class="form-select" id="addCategory">
        <% categories.each do |category| %>
          <option value='<%= category.id %>'><%= category.name %></option>
        <% end %>
      </select>
    </div>

    <!-- Select Weapon Type -->
    <div class="mb-3" id="addWeapons" style="display:none;">
      <%= form.label :rarity_id, 'Weapon' %>
      <br>
      <select class="form-select" id="addWeaponDropdown">
        <% weapons.each do |weapon| %>
          <option value='<%= weapon.id %>'><%= weapon.name %></option>
        <% end %>
      </select>
      <small>Note: Weapons Selection is only available when selecting the Weapons category.</small>
    </div>

    <!-- Select Rarity -->  
    <div class="mb-3">
      <%= form.label :rarity_id, 'Rarity' %>
      <select class="form-select mt-3" id="addRarity"></select>
      <small>Note: Rarity level affects the maximum allowed power.</small>
    </div>

    <!-- Item Power -->
    <div class="mb-3">
      <%= form.label :power, 'Item Power (Max 10)' %>
      <%= form.number_field :power, max: 10, min: 0, class: 'form-control', placeholder: 'Enter item power' %>
    </div>
    
    <!-- Add Effects -->
    <div class="form-group mt-4 mb-4">
      <div class="row">
        <div class="col">
          <%= form.label :effect_ids, 'Effects', id: "effectsLabel", class: "form-label" %>
        </div>

        <div class="col text-end">
          <button id="addEffectBtn" class="btn btn-sm btn-outline-primary">Add Effect</button>
          <button id="resetEffects" class="btn btn-sm btn-outline-danger">Reset All Effects</button>
        </div>
      </div>

      <select class="form-select mt-3" id="addEffect"></select>
      <small>Each effect will consume power, total power should not exceed 10</small>
    </div>

    <!-- Selected Effects -->
    <div class="mb-3">
      <h5>Selected Effects</h5>
      <ul id="selectedEffects" class="list-group"></ul>
    </div>

    <!-- Power Usage -->
    <div class="mb-3">
      <label for="powerProgress" class="form-label">Total Power Used</label>
      <div class="progress">
        <div id="powerProgress" class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="10"></div>
      </div>
      <small id="powerUsageText" class="form-text text-muted">Power used: 0/10</small>
    </div>

    <hr class="cool-hr">

    <div class="form-group">
      <button id="createItem" class="btn btn-outline-primary disabled">Create Object</button>
    </div>
  <% end %>
</div>

app/views/items/create_random.html.erb
<%= render "layouts/subheader", :locals => {:count => 0, :name => "Generate Items"} %>

<hr class="cool-hr">

<%= form_with url: create_random_items_path, method: :post, data: { turbo: false }, local: true do |form| %>
<div class="container overflow-hidden">
  <div class="row" style="height: 400px">

      <div class="col-5 text-center">
        <div class="form-group">
          <%= form.label :category_id, "Category", style: "font-weight: 600; margin: 0 10px; border-radius: 5px 0 0 5px; width: 180px;", class: "btn btn-primary" %>
          <%= form.collection_select :category_id, @categories, :id, :name, prompt: "Choose a category", class: "dropdown-menu" %>
        </div>

        <div class="form-group">
          <%= form.label :power_level, "Power", style: "font-weight: 600; margin: 0 10px; border-radius: 5px 0 0 5px; width: 180px;", class: "btn btn-primary" %>
          <%= form.select :power_level, options_for_select(@power_levels), prompt: "Choose power level", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :rarity, "Rarity", style: "font-weight: 600; margin: 0 10px; border-radius: 5px 0 0 5px; width: 180px;", class: "btn btn-primary" %>
          <%= form.collection_select :rarity, @rarities, :id, :name, prompt: "Choose rarity", class: "form-control" %>
        </div>

        <div class="form-group">
          
        </div>
      </div>

      <div class="col-1 vertical-span"></div>

      <div class="col-5" style="padding-left: 2%">
        <div class="card-group">
          <div class="card" style="width: 18rem; max-width: 400px; margin: 25px; border: 1px solid gray; border-radius: 5px;">
            <%= image_tag "hero.png", alt: "Hero Image", class: "img-fluid", style: "max-height: 275px" %>
            <div class="card-body">
              <h5 class="card-title">Creating something amazing... </h5>
              <p class="card-text">In here we can create a new object.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="text-center mt-5">
    <%= form.submit "Generate Item", class: "btn btn-lg btn-outline-primary " %>
    <hr class="cool-hr">
    <%= form.submit "Generate Fully Random Item", class: "btn btn-sm btn-success mt-2" %>
  </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<%= render "layouts/subheader", :locals => {:count => 0, :name => "Edit Item"} %>
<div class="text-center" style="">
	<%= link_to 'Back to Items Index', items_path, class: "btn btn-outline-primary mt-3" %>
</div>
<%= render 'form', item: @item, weapons: @weapons, effects: @effects, categories: @categories, rarities: @rarities %>

app/views/items/index.html.erb
<%= render "layouts/subheader", :locals => {:count => @items.count, :name => "Items"} %>

<div class="container mt-3">  
  <table class="table table-hover table-bordered table-striped">
    <thead class="table-primary">
      <tr>
      	<th>Id</th>
        <th>Item Name</th>
        <th>Category</th>
        <th>Rarity</th>
        <th>Requires Attunement</th>
        <th>Price (MO)</th>
        <th>Weight (lbs)</th>
        <th>Power</th>
        <th>Effect | Power | Type</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
        	<td><%= item.id %></td>
          <td><%= item.name %></td>
          <td><%= item.category.name %></td>
          <td><%= item.rarity.name %></td>
          <td><%= item.requires_attunement ? "Yes" : "No" %></td>
          <td><%= item.price %></td>
          <td><%= item.weight %></td>
          <td><%= item.power %></td>
          <td>
            <ul>
              <li>
                  <% item.effects.each_with_index do |effect, i| %>
                    <span class=""><%= "➜ Type: #{effect.effect_type} | Power: #{effect.power_level} | #{effect.description}" %></span>
                    <br>       
                  <% end %>
                </li>
            </ul>
          </td>
          <td style="min-width: 185px;">
          	<div style="display: flex; gap: 5px;">
            	<%= link_to 'Show', item_path(item), class: "btn btn-outline-primary btn-sm" %>
            	<%= link_to 'Edit', edit_item_path(item), class: "btn btn-outline-success btn-sm" %>
		         	<%= button_to 'Delete', item_path(item), method: :delete, data: { confirm: 'Are you sure you want to remove this item?' }, class: "btn btn-outline-danger btn-sm" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/new.html.erb
<%= render "layouts/subheader", :locals => {:count => 0, :name => "New Item"} %>
<div class="text-center" style="">
	<%= link_to 'Back to Items Index', items_path, class: "btn btn-outline-primary mt-3" %>
</div>
<%= render 'form', item: @item, weapons: @weapons, effects: @effects, categories: @categories, rarities: @rarities %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<p><%= @item.description %></p>
<p>Type: <%= @item.item_type %></p>
<p>Rarity: <%= @item.rarity %></p>
<p>Category: <%= @item.category.name %></p>

<h2>Effects</h2>
<% @item.effects.each do |effect| %>
  <p><%= effect.name %> - <%= effect.description %> (Power: <%= effect.power_level %>)</p>
<% end %>

<%= link_to 'Add Effect', new_item_effect_path(@item) %>
<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>